stages:
- build
- combine

build amd64:
  tags:
  - macos
  - amd64
  stage: build
  before_script:
  - export GO_LDFLAGS="-X main.Tag=$CI_COMMIT_TAG -X main.Commit=$CI_COMMIT_SHA -X 'main.BuildTime=`date '+%b %_d %Y, %H:%M:%S'`'"
  script:
  - mkdir mautrix-imessage-amd64
  - go build -ldflags "$GO_LDFLAGS" -o mautrix-imessage-amd64/mautrix-imessage
  - install_name_tool -change /usr/local/opt/libolm/lib/libolm.3.dylib @rpath/libolm.3.dylib mautrix-imessage-amd64/mautrix-imessage
  - install_name_tool -add_rpath @executable_path mautrix-imessage-amd64/mautrix-imessage
  - install_name_tool -add_rpath /usr/local/opt/libolm/lib mautrix-imessage-amd64/mautrix-imessage
  - cp /usr/local/opt/libolm/lib/libolm.3.dylib mautrix-imessage-amd64/
  - cp example-config.yaml mautrix-imessage-amd64/
  artifacts:
    paths:
    - mautrix-imessage-amd64

build arm64:
  tags:
  - macos
  - arm64
  stage: build
  before_script:
  - export GO_LDFLAGS="-X main.Tag=$CI_COMMIT_TAG -X main.Commit=$CI_COMMIT_SHA -X 'main.BuildTime=`date '+%b %_d %Y, %H:%M:%S'`'"
  - export LIBRARY_PATH=/opt/homebrew/lib
  - export CPATH=/opt/homebrew/include
  - export PATH=/opt/homebrew/bin:$PATH
  script:
  - mkdir mautrix-imessage-arm64
  - go build -ldflags "$GO_LDFLAGS" -o mautrix-imessage-arm64/mautrix-imessage
  - install_name_tool -change /opt/homebrew/opt/libolm/lib/libolm.3.dylib @rpath/libolm.3.dylib mautrix-imessage-arm64/mautrix-imessage
  - install_name_tool -add_rpath @executable_path mautrix-imessage-arm64/mautrix-imessage
  - install_name_tool -add_rpath /opt/homebrew/opt/libolm/lib mautrix-imessage-arm64/mautrix-imessage
  - install_name_tool -add_rpath /usr/local/opt/libolm/lib mautrix-imessage-arm64/mautrix-imessage
  - cp /opt/homebrew/opt/libolm/lib/libolm.3.dylib mautrix-imessage-arm64/
  - cp example-config.yaml mautrix-imessage-arm64/
  artifacts:
    paths:
    - mautrix-imessage-arm64

build armv7:
  tags:
  - macos
  - arm64
  stage: build
  variables:
    CGO_ENABLED: 1
    GOARCH: arm
    GOARM: 7
    GOPATH: /Users/ci/go-1.14
    GOROOT: /Users/ci/Library/Go1.14
  before_script:
  - export GO_LDFLAGS="-X main.Tag=$CI_COMMIT_TAG -X main.Commit=$CI_COMMIT_SHA -X 'main.BuildTime=`date '+%b %_d %Y, %H:%M:%S'`'"
  - export LIBRARY_PATH=/Users/ci/lib:/opt/homebrew/lib
  - export CPATH=/opt/homebrew/include
  - export PATH=$GOROOT/bin:/opt/homebrew/bin:$PATH
  - export CC=$(pwd)/armv7-clangwrap.sh
  - export CXX=$CC
  script:
  - go build -ldflags "$GO_LDFLAGS" -o mautrix-imessage
  - install_name_tool -change /Users/ci/lib/libolm.3.dylib @executable_path/libolm.3.dylib mautrix-imessage
  - cp /Users/ci/lib/libolm.3.dylib .
  artifacts:
    paths:
    - libolm.3.dylib
    - mautrix-imessage

build universal:
  stage: combine
  tags:
  - macos
  - arm64
  variables:
    GIT_STRATEGY: none
  dependencies:
  - build amd64
  - build arm64
  needs:
  - build amd64
  - build arm64
  script:
  - lipo -create -output libolm.3.dylib mautrix-imessage-arm64/libolm.3.dylib mautrix-imessage-amd64/libolm.3.dylib
  - lipo -create -output mautrix-imessage mautrix-imessage-arm64/mautrix-imessage mautrix-imessage-amd64/mautrix-imessage
  - cp mautrix-imessage-arm64/example-config.yaml .
  artifacts:
    name: mautrix-imessage-universal
    paths:
    - libolm.3.dylib
    - mautrix-imessage
    - example-config.yaml
